config/routes.rb
UWCATestingSystem::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, ActiveAdmin::Devise.config

  get "professor/home"

  get "professor/section"

  get "professor/test"

  get "professor/settings"

  resources :section_tests

  resources :answers

  resources :questions

  resources :student_tests

  resources :enrolled_students

  resources :sections

  resources :semesters

  resources :courses

  resources :users

end

app/models/student_test.rb
# == Schema Information
#
# Table name: student_tests
#
#  id                  :integer         not null, primary key
#  time_started        :datetime
#  time_submitted      :datetime
#  created_at          :datetime
#  updated_at          :datetime
#  enrolled_student_id :integer
#  section_test_id     :integer
#

# A collection of answers to a test created by a student.
class StudentTest < ActiveRecord::Base
  belongs_to :enrolled_student
  belongs_to :section_test
  has_many :answers

  attr_accessible :time_started, :time_submitted

  validates :enrolled_student,  :presence => true
  validates :section_test,      :presence => true

  # a shortcut to refer to the test's student
  def student
    enrolled_student.student
  end

  # A shortcut to refer to a test's section
  def section
    section_test.section
  end

  # The time take is the time the test was submitted minus the time it 
  # was started
  def time_taken
    @time_submitted - @time_started
  end

  # The sum of all marks earned by each answers.
  def earned_marks
    answers.map{ |x| x.earned_marks }.inject(0, :+)
  end

  # The percentage earned by this test.
  def percentage
    ( earned_marks / section_test.possible_marks ) * 100
  end

  # A test is submitted if the time it was submitted is not nil.
  def submitted?
    not @time_submitted.nil?
  end

  def all_answers_submitted?
    # maps answers to an array of booleans then checks if it contains a 
    # false. If it does not then all answers are submitted.
    not answers.map{ |x| x.submitted? }.include?(false)
  end

  # Returns true if all answers are marked.
  def marked?
    not answers.map{ |x| x.marked? }.include?(false)
  end

  # Returns true if the student test can still be modified by the student.
  def active?
    self.section_test.active? && ( not self.submitted? )
  end

end

app/controllers/student_tests_controller.rb
class StudentTestsController < ApplicationController
  # GET /student_tests
  # GET /student_tests.json
  def index
    @student_tests = StudentTest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_tests }
    end
  end

  # GET /student_tests/1
  # GET /student_tests/1.json
  def show
    @student_test = StudentTest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_test }
    end
  end

  # GET /student_tests/new
  # GET /student_tests/new.json
  def new
    @student_test = StudentTest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_test }
    end
  end

  # GET /student_tests/1/edit
  def edit
    @student_test = StudentTest.find(params[:id])
  end

  # POST /student_tests
  # POST /student_tests.json
  def create
    @student_test = StudentTest.new(params[:student_test])

    respond_to do |format|
      if @student_test.save
        format.html { redirect_to @student_test, notice: 'Student test was successfully created.' }
        format.json { render json: @student_test, status: :created, location: @student_test }
      else
        format.html { render action: "new" }
        format.json { render json: @student_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_tests/1
  # PUT /student_tests/1.json
  def update
    @student_test = StudentTest.find(params[:id])

    respond_to do |format|
      if @student_test.update_attributes(params[:student_test])
        format.html { redirect_to @student_test, notice: 'Student test was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_tests/1
  # DELETE /student_tests/1.json
  def destroy
    @student_test = StudentTest.find(params[:id])
    @student_test.destroy

    respond_to do |format|
      format.html { redirect_to student_tests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/student_tests_helper.rb
module StudentTestsHelper
end

app/views/student_tests/_form.html.erb
<%= form_for(@student_test) do |f| %>
  <% if @student_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_test.errors.count, "error") %> prohibited this student_test from being saved:</h2>

      <ul>
      <% @student_test.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_started %><br />
    <%= f.datetime_select :time_started %>
  </div>
  <div class="field">
    <%= f.label :time_submitted %><br />
    <%= f.datetime_select :time_submitted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_tests/edit.html.erb
<h1>Editing student_test</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_test %> |
<%= link_to 'Back', student_tests_path %>

app/views/student_tests/index.html.erb
<h1>Listing student_tests</h1>

<table>
  <tr>
    <th>Time started</th>
    <th>Time submitted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_tests.each do |student_test| %>
  <tr>
    <td><%= student_test.time_started %></td>
    <td><%= student_test.time_submitted %></td>
    <td><%= link_to 'Show', student_test %></td>
    <td><%= link_to 'Edit', edit_student_test_path(student_test) %></td>
    <td><%= link_to 'Destroy', student_test, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student test', new_student_test_path %>

app/views/student_tests/new.html.erb
<h1>New student_test</h1>

<%= render 'form' %>

<%= link_to 'Back', student_tests_path %>

app/views/student_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time started:</b>
  <%= @student_test.time_started %>
</p>

<p>
  <b>Time submitted:</b>
  <%= @student_test.time_submitted %>
</p>


<%= link_to 'Edit', edit_student_test_path(@student_test) %> |
<%= link_to 'Back', student_tests_path %>