config/routes.rb
UWCATestingSystem::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, ActiveAdmin::Devise.config

  get "professor/home"

  get "professor/section"

  get "professor/test"

  get "professor/settings"

  resources :section_tests

  resources :answers

  resources :questions

  resources :student_tests

  resources :enrolled_students

  resources :sections

  resources :semesters

  resources :courses

  resources :users

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id              :integer         not null, primary key
#  earned_marks    :float
#  time_taken      :float
#  time_submitted  :datetime
#  created_at      :datetime
#  updated_at      :datetime
#  student_test_id :integer
#  question_id     :integer
#  type            :string(255)
#  text            :text
#

# An abstract answer to a question.
class Answer < ActiveRecord::Base
  belongs_to :student_test
  belongs_to :question

  attr_accessible :earned_marks, :time_submitted, :time_taken

  validates :student_test,  :presence => true
  validates :question,      :presence => true

  validates :earned_marks,  :numericality => 
                            { :greater_than_or_equal_to => 0 },
                            :allow_nil => true

  after_initialize :default_values


  # An answer has been submitted if the time it was submitted is not nil.
  def submitted? 
    not @time_submitted.nil?
  end

  # The percentage of marks earned by this answer.
  def percentage
    (@earned_marks / self.question.possible_marks) * 100
  end

  # Returns true if answer has been assigned a value.
  def marked? 
    not @earned_marks.nil?
  end

  private 

    # Sets attributes to default values if nil
    def default_values
      self.time_taken = 0 if self.time_taken.nil?
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :earned_marks %><br />
    <%= f.text_field :earned_marks %>
  </div>
  <div class="field">
    <%= f.label :time_taken %><br />
    <%= f.number_field :time_taken %>
  </div>
  <div class="field">
    <%= f.label :time_submitted %><br />
    <%= f.datetime_select :time_submitted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Earned marks</th>
    <th>Time taken</th>
    <th>Time submitted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.earned_marks %></td>
    <td><%= answer.time_taken %></td>
    <td><%= answer.time_submitted %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Earned marks:</b>
  <%= @answer.earned_marks %>
</p>

<p>
  <b>Time taken:</b>
  <%= @answer.time_taken %>
</p>

<p>
  <b>Time submitted:</b>
  <%= @answer.time_submitted %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>