config/routes.rb
UWCATestingSystem::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, ActiveAdmin::Devise.config

  get "professor/home"

  get "professor/section"

  get "professor/test"

  get "professor/settings"

  resources :section_tests

  resources :answers

  resources :questions

  resources :student_tests

  resources :enrolled_students

  resources :sections

  resources :semesters

  resources :courses

  resources :users

end

app/models/enrolled_student.rb
# == Schema Information
#
# Table name: enrolled_students
#
#  id         :integer         not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  student_id :integer
#  section_id :integer
#

# A student associated with a scetion.
class EnrolledStudent < ActiveRecord::Base
  belongs_to :student
  belongs_to :section
  has_many :student_tests

  validates :student, :presence => true
  validates :section, :presence => true

  # The average mark of this student.
  def average_percentage
    total = student_tests.map{ |x| x.percentage }.inject(0, :+)
    total / student_tests.size
  end
end

app/controllers/enrolled_students_controller.rb
class EnrolledStudentsController < ApplicationController
  # GET /enrolled_students
  # GET /enrolled_students.json
  def index
    @enrolled_students = EnrolledStudent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enrolled_students }
    end
  end

  # GET /enrolled_students/1
  # GET /enrolled_students/1.json
  def show
    @enrolled_student = EnrolledStudent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enrolled_student }
    end
  end

  # GET /enrolled_students/new
  # GET /enrolled_students/new.json
  def new
    @enrolled_student = EnrolledStudent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enrolled_student }
    end
  end

  # GET /enrolled_students/1/edit
  def edit
    @enrolled_student = EnrolledStudent.find(params[:id])
  end

  # POST /enrolled_students
  # POST /enrolled_students.json
  def create
    @enrolled_student = EnrolledStudent.new(params[:enrolled_student])

    respond_to do |format|
      if @enrolled_student.save
        format.html { redirect_to @enrolled_student, notice: 'Enrolled student was successfully created.' }
        format.json { render json: @enrolled_student, status: :created, location: @enrolled_student }
      else
        format.html { render action: "new" }
        format.json { render json: @enrolled_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enrolled_students/1
  # PUT /enrolled_students/1.json
  def update
    @enrolled_student = EnrolledStudent.find(params[:id])

    respond_to do |format|
      if @enrolled_student.update_attributes(params[:enrolled_student])
        format.html { redirect_to @enrolled_student, notice: 'Enrolled student was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @enrolled_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolled_students/1
  # DELETE /enrolled_students/1.json
  def destroy
    @enrolled_student = EnrolledStudent.find(params[:id])
    @enrolled_student.destroy

    respond_to do |format|
      format.html { redirect_to enrolled_students_url }
      format.json { head :ok }
    end
  end
end

app/helpers/enrolled_students_helper.rb
module EnrolledStudentsHelper
end

app/views/enrolled_students/_form.html.erb
<%= form_for(@enrolled_student) do |f| %>
  <% if @enrolled_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrolled_student.errors.count, "error") %> prohibited this enrolled_student from being saved:</h2>

      <ul>
      <% @enrolled_student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrolled_students/edit.html.erb
<h1>Editing enrolled_student</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrolled_student %> |
<%= link_to 'Back', enrolled_students_path %>

app/views/enrolled_students/index.html.erb
<h1>Listing enrolled_students</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enrolled_students.each do |enrolled_student| %>
  <tr>
    <td><%= link_to 'Show', enrolled_student %></td>
    <td><%= link_to 'Edit', edit_enrolled_student_path(enrolled_student) %></td>
    <td><%= link_to 'Destroy', enrolled_student, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enrolled student', new_enrolled_student_path %>

app/views/enrolled_students/new.html.erb
<h1>New enrolled_student</h1>

<%= render 'form' %>

<%= link_to 'Back', enrolled_students_path %>

app/views/enrolled_students/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_enrolled_student_path(@enrolled_student) %> |
<%= link_to 'Back', enrolled_students_path %>