config/routes.rb
UWCATestingSystem::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, ActiveAdmin::Devise.config

  get "professor/home"

  get "professor/section"

  get "professor/test"

  get "professor/settings"

  resources :section_tests

  resources :answers

  resources :questions

  resources :student_tests

  resources :enrolled_students

  resources :sections

  resources :semesters

  resources :courses

  resources :users

end

app/models/section_test.rb
# == Schema Information
#
# Table name: section_tests
#
#  id             :integer         not null, primary key
#  name           :string(255)
#  description    :text
#  start_time     :datetime
#  end_time       :datetime
#  time_submitted :datetime
#  created_at     :datetime
#  updated_at     :datetime
#  section_id     :integer
#

# A collection of questions associated with a section and student tests.
class SectionTest < ActiveRecord::Base

  include MathHelper
  include TimeInfo

  has_many :questions
  has_many :student_tests
  belongs_to :section

  attr_accessible :name, :description
  attr_accessible :start_time, :end_time, :time_submitted

  validates :name,        :presence => true
  validates :start_time,  :presence => true
  validates :end_time,    :presence => true
  validates :section,     :presence => true

  # The sum of the possible marks of all non bonus questions.
  def possible_marks
    # Filter out all bonus questions, then maps them to their possible
    # marks and sums them together.
    questions.reject{ |x| x.bonus }.map{ |x| x.possible_marks }.
      inject(0, :+)
  end

  # The average marks earned by all the student test.
  def average_marks_earned
    total = student_tests.map{ |x| x.earned_marks }.inject(0, :+)
    total / student_tests.size
  end

  # The average percentage earned.
  def average_marks_earned_percentage
    ( average_marks_earned / possible_marks ) * 100
  end

  # The median marks earned by all the student tests.
  def median_marks_earned
    marks = student_test.map{ |x| x.earned_marks }
    median(marks)
  end

  # The average time taken to write all the student tests.
  def average_time_taken
    total = student_tests.map{ |x| x.time_taken }.inject(0, :+)
    total / student_tests.size
  end

  # The median time take to write all the student tests.
  def median_time_taken
    times = student_tests.map{ |x| x.time_taken }
    median(times)
  end

  # A test is submitted and it's marks are made available if the time 
  # submitted is not nil.
  def submitted?
    not @time_submitted.nil?
  end

  # Returns true if all student tests have been marked.
  def marked?
    not student_tests.map{ |x| x.marked? }.include?(false)
  end

end

app/controllers/section_tests_controller.rb
class SectionTestsController < ApplicationController
  # GET /section_tests
  # GET /section_tests.json
  def index
    @section_tests = SectionTest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @section_tests }
    end
  end

  # GET /section_tests/1
  # GET /section_tests/1.json
  def show
    @section_test = SectionTest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section_test }
    end
  end

  # GET /section_tests/new
  # GET /section_tests/new.json
  def new
    @section_test = SectionTest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section_test }
    end
  end

  # GET /section_tests/1/edit
  def edit
    @section_test = SectionTest.find(params[:id])
  end

  # POST /section_tests
  # POST /section_tests.json
  def create
    @section_test = SectionTest.new(params[:section_test])

    respond_to do |format|
      if @section_test.save
        format.html { redirect_to @section_test, notice: 'Section test was successfully created.' }
        format.json { render json: @section_test, status: :created, location: @section_test }
      else
        format.html { render action: "new" }
        format.json { render json: @section_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /section_tests/1
  # PUT /section_tests/1.json
  def update
    @section_test = SectionTest.find(params[:id])

    respond_to do |format|
      if @section_test.update_attributes(params[:section_test])
        format.html { redirect_to @section_test, notice: 'Section test was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @section_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section_tests/1
  # DELETE /section_tests/1.json
  def destroy
    @section_test = SectionTest.find(params[:id])
    @section_test.destroy

    respond_to do |format|
      format.html { redirect_to section_tests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/section_tests_helper.rb
module SectionTestsHelper
end

app/views/section_tests/_form.html.erb
<%= form_for(@section_test) do |f| %>
  <% if @section_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section_test.errors.count, "error") %> prohibited this section_test from being saved:</h2>

      <ul>
      <% @section_test.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :time_submitted %><br />
    <%= f.datetime_select :time_submitted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/section_tests/edit.html.erb
<h1>Editing section_test</h1>

<%= render 'form' %>

<%= link_to 'Show', @section_test %> |
<%= link_to 'Back', section_tests_path %>

app/views/section_tests/index.html.erb
<h1>Listing section_tests</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Time submitted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @section_tests.each do |section_test| %>
  <tr>
    <td><%= section_test.name %></td>
    <td><%= section_test.description %></td>
    <td><%= section_test.start_time %></td>
    <td><%= section_test.end_time %></td>
    <td><%= section_test.time_submitted %></td>
    <td><%= link_to 'Show', section_test %></td>
    <td><%= link_to 'Edit', edit_section_test_path(section_test) %></td>
    <td><%= link_to 'Destroy', section_test, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Section test', new_section_test_path %>

app/views/section_tests/new.html.erb
<h1>New section_test</h1>

<%= render 'form' %>

<%= link_to 'Back', section_tests_path %>

app/views/section_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @section_test.name %>
</p>

<p>
  <b>Description:</b>
  <%= @section_test.description %>
</p>

<p>
  <b>Start time:</b>
  <%= @section_test.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @section_test.end_time %>
</p>

<p>
  <b>Time submitted:</b>
  <%= @section_test.time_submitted %>
</p>


<%= link_to 'Edit', edit_section_test_path(@section_test) %> |
<%= link_to 'Back', section_tests_path %>